services:
  api-proxy:
    build: .
    container_name: api-proxy
    ports:
      - "3000:3000"
    volumes:
      # Mount data directory for SQLite database persistence
      - ./data:/app/data
      # Mount .env file if it exists
      - ./.env:/app/.env:ro
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s