name: 🐛 Bug Report
description: Report a bug or issue with LLM Proxy
title: "[Bug] "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us resolve the issue quickly.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-flight Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported already
          required: true
        - label: I have read the [documentation](https://github.com/caoergou/LLMProxy/blob/main/README.md)
          required: true
        - label: I can reproduce this issue consistently
          required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Desktop Application
        - Web Interface  
        - API Proxy
        - Provider Integration
        - Configuration
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "Describe what happened and what you expected to happen"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: "Describe the expected behavior"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior  
      description: What actually happened
      placeholder: "Describe what actually happened"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide information about your environment
      placeholder: |
        - OS: [e.g. Windows 11, macOS 13, Ubuntu 22.04]
        - LLM Proxy Version: [e.g. 1.0.0]
        - Node.js Version: [e.g. 18.17.0]
        - Browser: [e.g. Chrome 118] (if web interface issue)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: Any relevant log output or error messages
      placeholder: "Paste any error messages, logs, or stack traces here"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: "Add any other context about the problem here"
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: "Drag and drop screenshots here"
    validations:
      required: false